<div class="content-header">
    <table cellspacing="0"><tbody>
        <tr>
            <td style="width:50%;"><h3 class="icon-head"><?php echo $this->__('Cloudsearch Synchronization'); ?></h3></td>
            <td class="form-buttons">

                <?php echo $this->getMigrateButton() ?>

            </td>
        </tr>
    </tbody></table>
</div>
<div class="entry-edit">
	<form id="syncro" name="syncro" action="#" method="post">
		<div class="entry-edit-head">
			<h4><?php echo $this->__('Synchronization Data'); ?></h4>
		</div>
		<?php 
		$_helper=Mage::helper('upseller_clouldsearch');
		$apiuid=$_helper->getCloudsearchUid();
		$apikey=$_helper->getCloudsearchKey(); 
		//if($apiuid!="" || $apikey!=""){ ?>

			<div id="general_region" class="fieldset">
				<div class="hor-scroll">
					<table class="form-list" cellspacing="0">
						<tbody>
							
								<!--<tr class="nm">
							        <td class="label"><label for="username"><?php echo $this->__('Attributes'); ?></label></td>
								    <td class="value">
								        <input id="attributes" name="attributes" value="1" type="checkbox" class="checkbox" checked="checked" />
								    </td>
							    </tr>-->
							    <tr class="nm">
							        <td class="label"><label for="username"><?php echo $this->__('Store'); ?></label></td>
								    <td class="value">

								    	<?php $websites = Mage::app()->getWebsites(); ?>

								    	<select id="store_switcher" name="store" class="system-config-store-switcher">
								    		<?php foreach($websites as $website): ?>
								              <option value="<?php echo $website->getCode(); ?>" style="padding-left:16px; background:#DDD; font-weight:bold;" disabled="disabled"><?php echo $website->getName(); ?></option>
								              		<?php foreach ($website->getGroups() as $group) : ?>
									                    <optgroup label="<?php echo $group->getName(); ?>" style="padding-left:32px;">
									                          <?php $stores = $group->getStores(); ?>
									                          <?php foreach($stores as $store): ?>
									                          	<option value="<?php echo $store->getId(); ?>"><?php echo $store->getName(); ?></option>
									                    	  <?php endforeach; ?>	
									                    </optgroup>
									                <?php endforeach; ?>    
								            <?php endforeach; ?>        

								              
									    </select>

								    </td>
							    </tr>
							    <tr class="nm">
							        <td class="label"><label for="username"><?php echo $this->__('Products'); ?></label></td>
								    <td class="value">
								        <input id="products" name="products" value="1" type="checkbox" class="checkbox" checked="checked"  />
								    </td>
							    </tr>
							    <tr class="nm">
							        <td class="label"><label for="username"><?php echo $this->__('Categories'); ?></label></td>
								    <td class="value">
								        <input id="categories" name="categories" value="1" type="checkbox" class="checkbox" checked="checked"  />
								    </td>
							    </tr>
							  
						</tbody>
					</table>
				</div>
			</div>

		<?php //}else{ ?>

			<!--<div id="general_region" class="fieldset">

				<?php //echo Mage::Helper('upseller_clouldsearch')->__("Configuration is not Setup yet.") ?>
				<br>
				<?php //echo Mage::Helper('upseller_clouldsearch')->__("Go to here System -> Configuration -> Cloudsearch -> Setting and insert API Key and API UID") ?>

			</div>-->

		<?php //} ?>
			
	</form>  	
</div>

<div class="entry-edit" id="syncronizationdata">
<?php 
echo Mage::app()->getLayout()->createBlock('upseller_clouldsearch/adminhtml_synchronization_syncroinfo')->setTemplate('upseller/clouldsearch/synchronization/syncroinfo.phtml')->toHtml();
?>
</div>
<script type="text/javascript">
	function startSynchronization(){
		var object={};
		object['initurl']='<?php echo $this->getUrl("clouldsearch/adminhtml_synchronization/init"); ?>';
		object['continueurl']='<?php echo $this->getUrl("clouldsearch/adminhtml_synchronization/continue"); ?>';
		object['fromdata']=$('syncro').serialize(true);
		var cloudsearchSynchronizationInit = new cloudsearchSynchronization(object);
	}

</script>
